### PR TITLE
add UserByRestId and UsersByRestIds paths

### PR DESCRIPTION
**Pull request by rrika**

### CODE REVIEW

**Review by fa0311 — APPROVED** [review]
👍

**Comment by fa0311** [comment]
Thank you!
What client is this used for?
I looked for this on the web and could not find it.

**Comment by rrika** [comment]
I left the network monitor open for a long time and sometimes the web clients makes these requests, but I don't know when exactly. I think UserFromRestId happens sometimes when scrolling down a profile and UsersFromRestIds happens sometimes when looking at the notification list (and maybe clicking towards a thread)

**Comment by fa0311** [comment]
I see.

**Pull request merged**
